version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
      - ./core:/core
      - ./schemas:/schemas
      - ./mcp_clients:/mcp_clients
      - ./cli:/cli
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/netraven
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netraven
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # Uncomment below if you want to disable by default
    # deploy:
    #   replicas: 0
volumes:
  pgdata:
  ollama_data:
